//! Property-based tests — fuzz the state space to find disagreements
//! between the VM planning layer and the two-leg state model.
//!
//! Properties verified:
//! 1. VM's repo_push_action agrees with RepoState::push_action
//! 2. VM's repo_pull_action agrees with RepoState::pull_action
//! 3. plan_push never generates ops for in-sync repos
//! 4. plan_pull never generates ops for in-sync repos
//! 5. Merge against real repos never leaves conflict markers on target
//! 6. All ops generated by plan_push/plan_pull have valid preconditions

use proptest::prelude::*;
use gitvm::types::git::*;
use gitvm::vm::*;
use std::path::PathBuf;

// ============================================================================
// Strategies — generate random repo states
// ============================================================================

fn arb_ref_state() -> impl Strategy<Value = RefState> {
    prop_oneof![
        Just(RefState::Absent),
        "[a-f0-9]{7}".prop_map(RefState::At),
    ]
}

fn arb_repo_vm() -> impl Strategy<Value = RepoVM> {
    (arb_ref_state(), arb_ref_state(), arb_ref_state(), any::<bool>(), any::<bool>())
        .prop_map(|(container, session, target, container_clean, host_clean)| {
            let mut r = RepoVM::from_refs(container, session, target, Some(PathBuf::from("/tmp/fuzz")));
            r.container_clean = container_clean;
            r.host_clean = host_clean;
            r
        })
}

fn arb_leg_state() -> impl Strategy<Value = LegState> {
    prop_oneof![
        Just(LegState::InSync),
        (1u32..100).prop_map(|c| LegState::ContainerAhead { commits: c }),
        (1u32..100).prop_map(|c| LegState::SessionAhead { commits: c }),
        (1u32..100, 1u32..100).prop_map(|(ca, sa)| LegState::Diverged { container_ahead: ca, session_ahead: sa }),
        Just(LegState::Unknown),
        Just(LegState::NoSessionBranch),
        Just(LegState::NoContainer),
        Just(LegState::ContentIdentical),
    ]
}

fn arb_merge_leg() -> impl Strategy<Value = MergeLeg> {
    prop_oneof![
        Just(MergeLeg::NoTarget),
        Just(MergeLeg::InSync),
        (1u32..100).prop_map(|c| MergeLeg::SessionAhead { commits: c }),
        (1u32..100, any::<bool>()).prop_map(|(c, s)| MergeLeg::TargetAhead { commits: c, all_squash: s }),
        (1u32..100, 1u32..100).prop_map(|(sa, ta)| MergeLeg::Diverged { session_ahead: sa, target_ahead: ta }),
        Just(MergeLeg::ContentIdentical),
    ]
}

fn arb_blocker() -> impl Strategy<Value = Option<Blocker>> {
    prop_oneof![
        Just(None),
        (1u32..1000).prop_map(|n| Some(Blocker::ContainerDirty(n))),
        Just(Some(Blocker::ContainerMerging)),
        Just(Some(Blocker::ContainerRebasing)),
        Just(Some(Blocker::HostDirty)),
        Just(Some(Blocker::HostNotARepo(PathBuf::from("/tmp/x")))),
    ]
}

fn arb_repo_state() -> impl Strategy<Value = RepoState> {
    (arb_leg_state(), arb_merge_leg(), arb_blocker())
        .prop_map(|(extraction, merge, blocker)| RepoState { extraction, merge, blocker })
}

// ============================================================================
// Property 1: PushAction — host dirty doesn't block push
// ============================================================================

proptest! {
    #[test]
    fn push_action_never_blocked_by_host_dirty(
        extraction in arb_leg_state(),
        merge in arb_merge_leg(),
    ) {
        let state = RepoState {
            extraction,
            merge,
            blocker: Some(Blocker::HostDirty),
        };
        // Push should never be Blocked for HostDirty
        let action = state.push_action();
        prop_assert!(!matches!(action, PushAction::Blocked(Blocker::HostDirty)),
            "push should not be blocked by host dirty, got {:?}", action);
    }

    #[test]
    fn push_action_never_blocked_by_host_not_repo(
        extraction in arb_leg_state(),
        merge in arb_merge_leg(),
    ) {
        let state = RepoState {
            extraction,
            merge,
            blocker: Some(Blocker::HostNotARepo(PathBuf::from("/tmp/x"))),
        };
        let action = state.push_action();
        prop_assert!(!matches!(action, PushAction::Blocked(Blocker::HostNotARepo(_))),
            "push should not be blocked by host not a repo, got {:?}", action);
    }
}

// ============================================================================
// Property 2: Container-side blockers always block push
// ============================================================================

proptest! {
    #[test]
    fn push_blocked_by_container_dirty(
        extraction in arb_leg_state(),
        merge in arb_merge_leg(),
        n in 1u32..1000,
    ) {
        let state = RepoState {
            extraction,
            merge,
            blocker: Some(Blocker::ContainerDirty(n)),
        };
        let action = state.push_action();
        prop_assert!(matches!(action, PushAction::Blocked(_)),
            "container dirty should block push, got {:?}", action);
    }

    #[test]
    fn push_blocked_by_container_merging(
        extraction in arb_leg_state(),
        merge in arb_merge_leg(),
    ) {
        let state = RepoState {
            extraction,
            merge,
            blocker: Some(Blocker::ContainerMerging),
        };
        let action = state.push_action();
        prop_assert!(matches!(action, PushAction::Blocked(_)),
            "container merging should block push, got {:?}", action);
    }
}

// ============================================================================
// Property 3: Pull always blocked by any blocker
// ============================================================================

proptest! {
    #[test]
    fn pull_always_blocked_by_blocker(
        extraction in arb_leg_state(),
        merge in arb_merge_leg(),
        blocker in arb_blocker().prop_filter("must have blocker", |b| b.is_some()),
    ) {
        let state = RepoState {
            extraction,
            merge,
            blocker,
        };
        let action = state.pull_action();
        prop_assert!(matches!(action, PullAction::Blocked(_)),
            "pull should be blocked when blocker present, got {:?}", action);
    }
}

// ============================================================================
// Property 4: No blocker + InSync on both legs → both Skip
// ============================================================================

proptest! {
    #[test]
    fn in_sync_always_skips(
        _dummy in 0..1u32, // proptest needs at least one input
    ) {
        let state = RepoState {
            extraction: LegState::InSync,
            merge: MergeLeg::InSync,
            blocker: None,
        };
        prop_assert_eq!(state.pull_action(), PullAction::Skip);
        prop_assert_eq!(state.push_action(), PushAction::Skip);
    }
}

// ============================================================================
// Property 5: VM plan_push agrees with RepoState on "has push work"
// ============================================================================

proptest! {
    #[test]
    fn vm_plan_push_agrees_with_repo_state(
        repo_vm in arb_repo_vm(),
    ) {
        let mut vm = SyncVM::new("session", "main");
        vm.set_repo("alpha", repo_vm.clone());

        let ops = programs::plan_push(&vm);
        let vm_says_push = !ops.is_empty();

        // Build equivalent RepoState from the VM's repo
        // This is approximate — the VM's push_action uses different logic
        // (simple ref comparison) vs RepoState (ancestry-based).
        // The property we check: if all refs are identical, both agree no push needed.
        if repo_vm.container == repo_vm.session && repo_vm.session == repo_vm.target {
            prop_assert!(!vm_says_push,
                "all refs identical but VM says push needed");
        }
    }
}

// ============================================================================
// Property 6: plan_push ops all have valid preconditions
// ============================================================================

proptest! {
    #[test]
    fn plan_push_ops_have_valid_preconditions(
        repo_vm in arb_repo_vm(),
    ) {
        let mut vm = SyncVM::new("session", "main");
        vm.set_repo("alpha", repo_vm);

        let ops = programs::plan_push(&vm);
        for op in &ops {
            let result = op.check_preconditions(&vm);
            prop_assert!(result.is_ok(),
                "plan_push generated op with failed precondition: {:?} → {:?}", op, result.err());
        }
    }
}

// ============================================================================
// Property 7: plan_pull ops all have valid preconditions
// ============================================================================

proptest! {
    #[test]
    fn plan_pull_ops_have_valid_preconditions(
        repo_vm in arb_repo_vm(),
    ) {
        let mut vm = SyncVM::new("session", "main");
        vm.set_repo("alpha", repo_vm);

        let ops = programs::plan_pull(&vm);
        for op in &ops {
            let result = op.check_preconditions(&vm);
            prop_assert!(result.is_ok(),
                "plan_pull generated op with failed precondition: {:?} → {:?}", op, result.err());
        }
    }
}

// ============================================================================
// Property 8: Merge on real repos never leaves markers on target
// ============================================================================

proptest! {
    #![proptest_config(ProptestConfig::with_cases(20))] // fewer cases — each creates a repo

    #[test]
    fn merge_never_leaves_markers(
        main_content in "[a-z]{5,20}",
        session_content in "[a-z]{5,20}",
        conflict in any::<bool>(),
    ) {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("prop-merge");
        std::fs::create_dir_all(&path).unwrap();

        let (main_h, session_h) = {
            let repo = git2::Repository::init(&path).unwrap();
            let sig = git2::Signature::now("test", "test@test.com").unwrap();

            // Initial commit
            std::fs::write(path.join("file.txt"), "base\n").unwrap();
            let mut index = repo.index().unwrap();
            index.add_path(std::path::Path::new("file.txt")).unwrap();
            index.write().unwrap();
            let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
            repo.commit(Some("refs/heads/main"), &sig, &sig, "init", &tree, &[]).unwrap();
            repo.set_head("refs/heads/main").unwrap();
            repo.checkout_head(Some(git2::build::CheckoutBuilder::new().force())).unwrap();

            // Create session branch
            let head = repo.head().unwrap().peel_to_commit().unwrap();
            repo.branch("session", &head, false).unwrap();

            // Commit on main
            let main_file = if conflict { "file.txt" } else { "main.txt" };
            std::fs::write(path.join(main_file), &main_content).unwrap();
            let mut index = repo.index().unwrap();
            index.add_path(std::path::Path::new(main_file)).unwrap();
            index.write().unwrap();
            let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
            let parent = repo.head().unwrap().peel_to_commit().unwrap();
            repo.commit(Some("HEAD"), &sig, &sig, "main", &tree, &[&parent]).unwrap();

            let main_ref = repo.find_reference("refs/heads/main").unwrap();
            let main_h = main_ref.peel_to_commit().unwrap().id().to_string();

            // Commit on session
            repo.set_head("refs/heads/session").unwrap();
            repo.checkout_head(Some(git2::build::CheckoutBuilder::new().force())).unwrap();
            let session_file = if conflict { "file.txt" } else { "session.txt" };
            std::fs::write(path.join(session_file), &session_content).unwrap();
            let mut index = repo.index().unwrap();
            index.add_path(std::path::Path::new(session_file)).unwrap();
            index.write().unwrap();
            let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
            let parent = repo.head().unwrap().peel_to_commit().unwrap();
            repo.commit(Some("HEAD"), &sig, &sig, "session", &tree, &[&parent]).unwrap();

            let session_ref = repo.find_reference("refs/heads/session").unwrap();
            let session_h = session_ref.peel_to_commit().unwrap().id().to_string();

            // Switch back to main
            repo.set_head("refs/heads/main").unwrap();
            repo.checkout_head(Some(git2::build::CheckoutBuilder::new().force())).unwrap();

            (main_h, session_h)
        };

        // Use SyncBackend to merge
        let docker = bollard::Docker::connect_with_local_defaults().unwrap();
        let engine = gitvm::sync::SyncEngine::new(docker);
        let _ = engine.merge(&path, "session", "main", true);

        // THE PROPERTY: no conflict markers on main, ever
        let repo = git2::Repository::open(&path).unwrap();
        let main_ref = repo.find_reference("refs/heads/main").unwrap();
        let main_commit = main_ref.peel_to_commit().unwrap();
        let tree = main_commit.tree().unwrap();
        let mut found_markers = None;
        tree.walk(git2::TreeWalkMode::PreOrder, |dir, entry| {
            if let Some(git2::ObjectType::Blob) = entry.kind() {
                let blob = repo.find_blob(entry.id()).unwrap();
                let content = std::str::from_utf8(blob.content()).unwrap_or("");
                if content.contains("<<<<<<<") {
                    let name = if dir.is_empty() { entry.name().unwrap_or("?").to_string() }
                              else { format!("{}{}", dir, entry.name().unwrap_or("?")) };
                    found_markers = Some(name);
                    return git2::TreeWalkResult::Abort;
                }
            }
            git2::TreeWalkResult::Ok
        }).unwrap();
        prop_assert!(found_markers.is_none(),
            "conflict markers on main in {:?}", found_markers);
    }
}
